services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: always
