services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    restart: always
