/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFavoritesRouteRouteImport } from './routes/_authenticated/favorites/route'
import { Route as authSignupRouteRouteImport } from './routes/(auth)/signup/route'
import { Route as authLoginRouteRouteImport } from './routes/(auth)/login/route'
import { Route as AuthenticatedLocationLocationNameRouteRouteImport } from './routes/_authenticated/location/$locationName/route'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_authenticated.lazy').then((d) => d.Route),
)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRouteRoute =
  AuthenticatedFavoritesRouteRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const authSignupRouteRoute = authSignupRouteRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRouteRoute = authLoginRouteRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLocationLocationNameRouteRoute =
  AuthenticatedLocationLocationNameRouteRouteImport.update({
    id: '/location/$locationName',
    path: '/location/$locationName',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/location/$locationName/route.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRouteRoute
  '/signup': typeof authSignupRouteRoute
  '/favorites': typeof AuthenticatedFavoritesRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/location/$locationName': typeof AuthenticatedLocationLocationNameRouteRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRouteRoute
  '/signup': typeof authSignupRouteRoute
  '/favorites': typeof AuthenticatedFavoritesRouteRoute
  '/': typeof AuthenticatedIndexRoute
  '/location/$locationName': typeof AuthenticatedLocationLocationNameRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/login': typeof authLoginRouteRoute
  '/(auth)/signup': typeof authSignupRouteRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRouteRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/location/$locationName': typeof AuthenticatedLocationLocationNameRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/favorites'
    | '/'
    | '/location/$locationName'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/favorites' | '/' | '/location/$locationName'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authenticated/favorites'
    | '/_authenticated/'
    | '/_authenticated/location/$locationName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authLoginRouteRoute: typeof authLoginRouteRoute
  authSignupRouteRoute: typeof authSignupRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/location/$locationName': {
      id: '/_authenticated/location/$locationName'
      path: '/location/$locationName'
      fullPath: '/location/$locationName'
      preLoaderRoute: typeof AuthenticatedLocationLocationNameRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFavoritesRouteRoute: typeof AuthenticatedFavoritesRouteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLocationLocationNameRouteRoute: typeof AuthenticatedLocationLocationNameRouteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFavoritesRouteRoute: AuthenticatedFavoritesRouteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLocationLocationNameRouteRoute:
    AuthenticatedLocationLocationNameRouteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authLoginRouteRoute: authLoginRouteRoute,
  authSignupRouteRoute: authSignupRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
